### ISSUE TITLE
make failed on debian wheezy

### ISSUE THREAD

**Issue by desin24** [SinclairQL/sQLux#2]
/usr/bin/ld: Warning: size of symbol `table' changed from 8 in general.o to 408 in //usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-5.0.so
/usr/bin/ld: general.o: undefined reference to symbol 'table'
//usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-5.0.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:46: recipe for target 'qlux' failed

no problems on debian stretch

**Comment by xXorAa** [comment]
This was fixed a while ago by renaming table to qlux_table
