### ISSUE TITLE
Keys don't work as expectetd 

### ISSUE THREAD

**Issue by desin24** [SinclairQL/sQLux#3]
F1 to F5 are ok
F6 to F10 only work as Shift+F1 to F5
dec 43 hex 2B =  is nowhere 
dec 58 hex 3A  :  is nowhere
the numpad is disabled

thanks for your hard work

**Comment by RWAP** [comment]
The QL only supports F1 to F5.  F6 to F10 are therefore Shift F1 to Shift F5.

Were you expecting something else?

**Comment by desin24** [comment]
Am 27.03.2017 um 10:47 schrieb Rich M:
> The QL only supports F1 to F5.  F6 to F10 are therefore Shift F1 to Shift F5.
>
> Were you expecting something else?
>
of course not !

i will saw off the numpad and remove the the superfluous F-keys

or is there a QL-stile USB Keyboard ?

Greetings from Switzerland

			Markus

**Comment by RWAP** [comment]
The question was whether F6 to F10 function as SHIFT F1 to SHIFT F5 as expected...

I agree - it would be useful to implement the numpad

**Comment by desin24** [comment]
sorry i am no C writer 
i can compile half of the programs under linux 

what keyboard layout and what locales  do you use ? 

i did some search 
http://www.jose.it-berater.org/sdl/core/sdl_keysym.htm
https://godoc.org/github.com/veandco/go-sdl2/sdl
https://gist.github.com/g2p/8597984

Greetings from Switzerland
                              Markus

**Comment by xXorAa** [comment]
Its currently USA keyboard with no locales.

**Comment by desin24** [comment]
Thanks 
installing to locales for en-US and switching the keyboard layout to US works
