### ISSUE TITLE
SPEED command doesn't appear to work

### ISSUE THREAD

**Issue by atoone** [SinclairQL/sQLux#33]
Setting SPEED = 1.0 in the .ini file doesn't appear to slow down the emulation at all, still running at full speed?

(BTW - fantastic to see this being updated! Thanks)

**Comment by xXorAa** [comment]
What version are you running?

**Comment by atoone** [comment]
Ah... the wrong one it turns out! Followed a link to the "latest release", and ended up a few behind.

I've downloaded the latest version and it's spot on. Again, thank you for keeping working on this.
