### ISSUE TITLE
sQLux KBD Not working

### ISSUE THREAD

**Issue by derek2210** [SinclairQL/sQLux#40]
The KBD option in the configuration files does not change the language from USA default.

**Comment by derek2210** [comment]
I have tried compiling v1.0.4, v1.0.5, v1.0.6 the keyboard mapping via the KBD option in the configuration file all work.

Only the Master repository the KBD option does not change from GE

**Comment by xXorAa** [comment]
I have tested here, and keymaps are switching as expected. For example in GB mode the [`] key becomes the [#] key!

**Comment by derek2210** [comment]
Hi,

Thank you for the update, but I followed the build instructions, cloned 
the git repository, built the executable as instructed.

Running the executable gives the " key as @ and @ as " should be the 
other way around.

works perfectly in v1.0.6.

**Comment by xXorAa** [comment]
Can you confirm your bug was actually missing @" translation and not the keymap switching being broken? If so this is now fixed!

**Comment by derek2210** [comment]
The bug is:

<SHIFT><2> gives @
<SHIFT><'> gives"

The SDL2screen.c file in v1.0.6 has been written differentialy from the 
Master SDL2screen.c

Regards,
Derek

**Comment by derek2210** [comment]
All fixed, thank you for the updates and trouble you went to...
