### ISSUE TITLE
"WIN_SIZE = max" runs as "WIN_SIZE = 1x"

### ISSUE THREAD

**Issue by SimonGreenaway** [SinclairQL/sQLux#49]
WINSIZE max does not max anything. If not supported --help and docs should be adjusted.

**Comment by xXorAa** [comment]
It works as designed, just tested it!

**Comment by SimonGreenaway** [comment]
This:

# sQLux configuration file

SYSROM = MIN198.rom
ROMDIR = /home/simon/emulators/ql/emulators/sQLux/roms
RAMTOP = 1024
CPU_HOG = 0
FAST_STARTUP = 1
SKIP_BOOT = 0
ROMPORT = TK232.rom
NO_PATCH = 0
BOOT_DEVICE = mdv1
WIN_SIZE = max
FILTER = 0
FIXASPECT = 1
KEYBOARD = UK
SPEED = 1
SOUND = 4
simon@laptop5:~/.sqlux$ ql --config /home/simon/.sqlux/minerva.ini 
Loading Config from: sqlux.ini
*** sQLux release v1.0.6-24-gef5687a-(2023-12-04)

using Minerva ROM
Emulation Speed: 1.0
sound enabled, volume 4.
Video Driver x11 xres 1920 yres 1080
Using default keymap. (use KBD=<countrycode> in sqlux.ini to change)

Result in a x1 sized window.

**Comment by SimonGreenaway** [comment]
As long as it's not me!
