### ISSUE TITLE
change to cmake breaks compilation. 

### ISSUE THREAD

**Issue by varmfskii** [SinclairQL/sQLux#5]
source as is requires path to SDL2 headers and linking with libsdl2, but the makefile produced by cmake provides neither of these.

header issue (with command make in build directory):

[  4%] Building C object CMakeFiles/sqlux.dir/QDisk.c.o
In file included from /home/alex/retro/ql/sQLux/QDisk.c:30:
/home/alex/retro/ql/sQLux/SDL2screen.h:4:10: fatal error: SDL.h: No such file or directory
    4 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/sqlux.dir/build.make:95: CMakeFiles/sqlux.dir/QDisk.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/sqlux.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

Library issue (compiled with C_LIBRARY_PATH=/usr/include/SDL2 make):
 
[ 97%] Linking C executable sqlux
/usr/bin/ld: CMakeFiles/sqlux.dir/SDL2screen.c.o: in function `QLSDL50Hz':
SDL2screen.c:(.text+0x12): undefined reference to `SDL_AtomicSet'
/usr/bin/ld: CMakeFiles/sqlux.dir/SDL2screen.c.o: in function `QLSDLScreen':
SDL2screen.c:(.text+0x1e4): undefined reference to `SDL_Init'
/usr/bin/ld: SDL2screen.c:(.text+0x1f1): undefined reference to `SDL_GetCurrentVideoDriver'
/usr/bin/ld: SDL2screen.c:(.text+0x206): undefined reference to `SDL_GetCurrentDisplayMode'
/usr/bin/ld: SDL2screen.c:(.text+0x28b): undefined reference to `SDL_CreateWindow'
/usr/bin/ld: SDL2screen.c:(.text+0x2a3): undefined reference to `SDL_GetWindowID'
/usr/bin/ld: SDL2screen.c:(.text+0x2bf): undefined reference to `SDL_CreateRenderer'
/usr/bin/ld: SDL2screen.c:(.text+0x2d6): undefined reference to `SDL_GetRendererOutputSize'
/usr/bin/ld: SDL2screen.c:(.text+0x2f5): undefined reference to `SDL_SetHint'
/usr/bin/ld: SDL2screen.c:(.text+0x308): undefined reference to `SDL_SetHint'
/usr/bin/ld: SDL2screen.c:(.text+0x326): undefined reference to `SDL_CreateRGBSurfaceWithFormat'
/usr/bin/ld: SDL2screen.c:(.text+0x365): undefined reference to `SDL_CreateTexture'
/usr/bin/ld: SDL2screen.c:(.text+0x390): undefined reference to `SDL_MapRGB'
/usr/bin/ld: SDL2screen.c:(.text+0x3a6): undefined reference to `SDL_AtomicSet'
/usr/bin/ld: SDL2screen.c:(.text+0x3b9): undefined reference to `SDL_AddTimer'
/usr/bin/ld: SDL2screen.c:(.text+0x431): undefined reference to `SDL_GetError'
/usr/bin/ld: SDL2screen.c:(.text+0x471): undefined reference to `SDL_GetError'
/usr/bin/ld: CMakeFiles/sqlux.dir/SDL2screen.c.o: in function `QLSDLUpdateScreenWord':
SDL2screen.c:(.text+0x74c): undefined reference to `SDL_UnlockSurface'
/usr/bin/ld: SDL2screen.c:(.text+0x759): undefined reference to `SDL_LockSurface'
/usr/bin/ld: CMakeFiles/sqlux.dir/SDL2screen.c.o: in function `QLSDLUpdatePixelBuffer':
SDL2screen.c:(.text+0xb37): undefined reference to `SDL_LockSurface'
/usr/bin/ld: CMakeFiles/sqlux.dir/SDL2screen.c.o: in function `QLSDLRenderScreen':
SDL2screen.c:(.text+0xb6c): undefined reference to `SDL_AtomicGet'
/usr/bin/ld: SDL2screen.c:(.text+0xb98): undefined reference to `SDL_UpdateTexture'
/usr/bin/ld: SDL2screen.c:(.text+0xba4): undefined reference to `SDL_RenderClear'
/usr/bin/ld: SDL2screen.c:(.text+0xbca): undefined reference to `SDL_RenderCopyEx'
/usr/bin/ld: SDL2screen.c:(.text+0xbd6): undefined reference to `SDL_RenderPresent'
/usr/bin/ld: CMakeFiles/sqlux.dir/SDL2screen.c.o: in function `QLSDLProcessEvents':
SDL2screen.c:(.text+0xde4): undefined reference to `SDL_PollEvent'
/usr/bin/ld: SDL2screen.c:(.text+0xe28): undefined reference to `SDL_PollEvent'
/usr/bin/ld: SDL2screen.c:(.text+0xe38): undefined reference to `SDL_AtomicGet'
/usr/bin/ld: SDL2screen.c:(.text+0xe58): undefined reference to `SDL_UpdateTexture'
/usr/bin/ld: SDL2screen.c:(.text+0xe64): undefined reference to `SDL_RenderClear'
/usr/bin/ld: SDL2screen.c:(.text+0xe8a): undefined reference to `SDL_RenderCopyEx'
/usr/bin/ld: SDL2screen.c:(.text+0xe96): undefined reference to `SDL_RenderPresent'
/usr/bin/ld: SDL2screen.c:(.text+0xea4): undefined reference to `SDL_AtomicSet'
/usr/bin/ld: SDL2screen.c:(.text+0xf7a): undefined reference to `SDL_GetRendererOutputSize'
/usr/bin/ld: SDL2screen.c:(.text+0xf98): undefined reference to `SDL_AtomicSet'
/usr/bin/ld: CMakeFiles/sqlux.dir/SDL2screen.c.o: in function `QLSDLUpdateScreenWord':
SDL2screen.c:(.text+0x68b): undefined reference to `SDL_AtomicSet'
/usr/bin/ld: CMakeFiles/sqlux.dir/SDL2screen.c.o: in function `QLSDLUpdatePixelBuffer':
SDL2screen.c:(.text+0xb2f): undefined reference to `SDL_UnlockSurface'
/usr/bin/ld: CMakeFiles/sqlux.dir/SDL2screen.c.o: in function `QLSDLRenderScreen':
SDL2screen.c:(.text+0xbe8): undefined reference to `SDL_AtomicSet'
/usr/bin/ld: CMakeFiles/sqlux.dir/SDL2screen.c.o: in function `QLSDLExit':
SDL2screen.c:(.text+0xfd1): undefined reference to `SDL_Quit'
/usr/bin/ld: CMakeFiles/sqlux.dir/iexl_general.c.o: in function `ExecuteLoop':
iexl_general.c:(.text+0x1d32): undefined reference to `SDL_AtomicGet'
/usr/bin/ld: CMakeFiles/sqlux.dir/unixstuff.c.o: in function `dosignal':
unixstuff.c:(.text+0x2ae): undefined reference to `SDL_AtomicSet'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/sqlux.dir/build.make:748: sqlux] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/sqlux.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**Comment by xXorAa** [comment]
It seems to be working correctly on my Linux and macOS systems.

Extract from Makefile on macOS

CMakeFiles/sqlux.dir/flags.make:7:C_INCLUDES = -I/opt/homebrew/Cellar/sdl2/2.0.12_1/include/SDL2

**Comment by xXorAa** [comment]
Cannot repeat and no further information has been posted.
