### ISSUE TITLE
Add way to quit emulator from within the emulator!

### ISSUE THREAD

**Issue by SimonGreenaway** [SinclairQL/sQLux#52]
I use the emulator for various tasks during a makefile build (e.g. zip), so it would be useful if there was someway  to quit the emulator rather  than it just sits there waiting for me to close it.

A secret 'CALL magic_number' maybe? Outside physiscal address range?

**Comment by ppe** [comment]
KILL_UQLX is a basic keyword you can use to exit the emulator.
