### ISSUE TITLE
MDV1_boot    get the QL feeling

### ISSUE THREAD

**Issue by desin24** [SinclairQL/sQLux#59]
100 REMark sQLux
110 OPEN   #4,con_512x202a0x0
120 BORDER #4,2,4,2
130 PAPER  #4,2:INK#4,7
140 CLS    #4
150 AT     #4, 1,9
160 CSIZE  #4, 3,1
170 PRINT  #4, "Welcome to sQLux"
180 CSIZE  #4,0,0
190 PRINT  #4
200 PRINT_RELEASE
210 PRINT  #4
220 PRINT  #4
230 PRINT  #4,"  Date",DATE$,"QDOS version:",VER$
240 PRINT  #4
250 PRINT  #4,"  Ram Size: ";(PEEK_L(163872)/1024 - 128);"k"
260 PRINT  #4
270 PRINT  #4,"  Start as: '";getXarg$(0);" -h' to get a list of startup options"
275 PRINT  #4
280 PRINT  #4,"  Quit with:  kill_uqlx"
290 CSIZE  #4,0,0
300 PRINT  #4
310 PRINT  #4,"  .... press any key"
320 PAUSE
321 CLS    #4
322 CLOSE  #4
350 WINDOW #1,256,202,256,0
360 WINDOW #2,256,202,0,0
361 CLS    #1
362 CLS    #2
372 :
400 DEFine PROCedure PRINT_RELEASE
410  STRIP #4,0
420  AT    #4,4,11
430  PRINT #4,"release"!!UQLX_RELEASE$
440  STRIP #4,2
450 END DEFine
460 :
470 DEFine PROCedure sa
480  DELETE 'mdv1_BOOT'
490  SAVE   'mdv1_BOOT'
500 END DEFine

**Comment by xXorAa** [comment]
Aplied thanks!
