### ISSUE TITLE
build issues under arch linux

### ISSUE THREAD

**Issue by varmfskii** [SinclairQL/sQLux#6]
The build issue is specific to how Arch linux exports the configuration to SDL2 to cmake.
it is a public export.
find_package(SDL2 REQUIRED) finds the package, but doesn't set anything
it is necessary to add the line: target_link_directory(sqlux SDL2::SDL2)

**Comment by varmfskii** [comment]
some additional info: [https://discourse.libsdl.org/t/arch-linux-cmake-find-package-sdl2-required-passes-but-doesnt-find-anything/24226/2](url)

**Comment by xXorAa** [comment]
That looks like arch has purposely chosen to break SDL2, I cant really fix arch linux!

**Comment by xXorAa** [comment]
Can you try this diff please?

diff --git a/CMakeLists.txt b/CMakeLists.txt
index cd90dfe..b501cb2 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -23,6 +23,10 @@ endif()
 find_package(SDL2 REQUIRED)
 include_directories(${SDL2_INCLUDE_DIRS})

+if(NOT ${SDL2_LIBRARIES})
+       set (SDL2_LIBRARIES "SDL2::SDL2")
+endif()
+
 add_executable(sqlux Init.c QDisk.c QL_basext.c QL_boot.c QL_cconv.c QL_config.c QL_driver.c QL_files.c QL_hardware.c QL_poll.c QL_screen.c QL_serial.c QL_sound.c QLip.c QLserio.c QLtraps.c QVFS.c SDL2screen.c Xscreen.c block.c dummies.c general.c ide.c iexl_general.c instructions_ao.c instructions_pz.c mach_exception.c memaccess.c pty.c qmtrap.c script.c trace.c unixstuff.c uqlx_cfg.c util.c uxfile.c version.c vl.c vm.c xc68.c xcodes.c xipc.c xlmain.c xqlmouse.c)
 target_link_libraries(sqlux m ${SDL2_LIBRARIES})

**Comment by varmfskii** [comment]
I'll try it, it looks viable.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by varmfskii** [comment]
It's no good.
it looks necessary to check if SDL2:SDL2 is set and if so, add the line "target_link_libraries(sqlux SDL2:SDL2)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by xXorAa** [comment]
Feel free to send a pull request, as long as it doesnt break other platforms Ill accept it!

**Comment by varmfskii** [comment]
Give me a bit and I'll do so (after some checking in other linuxes)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by xXorAa** [comment]
PR7 fixes this
