### ISSUE TITLE
Define Boot Device Directory

### ISSUE THREAD

**Issue by derek2210** [SinclairQL/sQLux#8]
The boot device can be defined in the command line with the option:

-d MDV1

But the directory of definition can only be defined in the configuration file.

Can the directory of a boot device be specified in the command line, e.g.

sQLux -d MDV1 -f ~/sQLux/MDV1

So that a Superbasic file saved can be loaded with the -b option, e.g.

SQLux -d MDV1 -f ~/sQLux/MDV1 -b MDV1_program_bas

**Comment by xXorAa** [comment]
I assume you mean -b 'lrun "mdv1_program_bas"' above?

**Comment by derek2210** [comment]
Sorry, I forgot to enter the lrun part in the in the -b option.

My plan was to edit a Superbasic file in VIM then save the file and run a BASH script containing the sQLux emulator string:

~/sQLux/sqlux -w 2x -b "lrun mdv1_$1" 

Where $1 is the name of the Superbasic programme.

A nice feature would be to define a QDOS device, i.e. MDV1 from the command line, e.g. -q "MDV1 ~/Superbasic"

I selected -q as an example, but can be anything.

**Comment by xXorAa** [comment]
I implented this as a way to send any sqlux.ini line from the cmdline.

./sqlux -c "DEVICE = FLP1,/tmp/flp.img,qdos-native"

Commit 9bab920d6a622b795f51e30fc125ee1598e2d595 in repo adds this support.
